config/routes.rb
Bookstore::Application.routes.draw do
  
  get "sessions/new"

  get "users/new"
  
  resources :books
  resources :authors
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :orders
  
  match '/books_search',  :to => 'shop#books_search'
  match '/authors_search', :to => 'shop#authors_search'
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/checkout', :to => 'orders#checkout'
  match '/done', :to => 'orders#done'

  match '/signup',  :to => 'users#new'
  match '/add_to_cart', :to => 'shop#add_to_cart'
  match '/clear_cart', :to => 'shop#clear_cart'
  match '/view_cart', :to => 'shop#view_cart'
  
	match '/watch_video', :to => 'shop#watch_video'
  match '/home_index', :to => 'shop#index'
  
  root :to => "shop#index"
  

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_and_belongs_to_many :books
  validates_uniqueness_of :id
  validates_presence_of :first_name, :last_name
  validates_uniqueness_of :first_name, :scope => :last_name
  validates_length_of :first_name, :last_name, :within => 2..20
  validates_format_of :first_name, :last_name, :with => /\A([A-Za-z\'\.-]*)\Z/
  
    # Searches for authors when called from controller using split and like
  def self.search(query)
    name = []
	name = query.to_s.gsub(/%/,"\%").split(" ")
	authors_arr = []
	authors_arr << Author.find_by_first_name_and_last_name(name[0], name[1]) unless Author.find_by_first_name_and_last_name(name[0], name[1]) == nil
	name.each do |i|
	  authors1 = Author.find(:all, :conditions => ["first_name like ?", "%#{i}%"])
	  authors1.each do |author|
		authors_arr << author unless authors_arr.include?(author)
	  end
	  authors1 = Author.find(:all, :conditions => ["last_name like ?", "%#{i}%"])
	  authors1.each do |author|
		authors_arr << author unless authors_arr.include?(author)
	  end
	end
	return authors_arr
  end
  
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_filter :run_before, :except => [:index, :show, :new, :edit, :destroy]
  
  def run_before
    params[:author][:first_name] = params[:author][:first_name].humanize.titleize
	params[:author][:last_name] = params[:author][:last_name].humanize.titleize
  end
  # GET /authors
  # GET /authors.xml
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.xml
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.xml
  def new
    @author = Author.new
	@books = Book.find(:all, :order => 'title')

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
	@books = Book.find(:all, :order => 'title')
  end

  # POST /authors
  # POST /authors.xml
  def create
    puts params[:author].class
    @author = Author.new(params[:author])
    respond_to do |format|
      if @author.save
        format.html { redirect_to(@author, :notice => 'Author was successfully created.') }
        format.xml  { render :xml => @author, :status => :created, :location => @author }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @author.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.xml
  def update
	@author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to(@author, :notice => 'Author was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @author.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.xml
  def destroy
    @author = Author.find(params[:id])

	if @author.books.empty?
	  @author.destroy
      respond_to do |format|
        format.html { redirect_to(authors_url) }
        format.xml  { head :ok }
      end
	else
	  respond_to do |format|
	    format.html { redirect_to(authors_url) }
        # flash[:notice] = "Author can't be deleted; remove all relared books first."
		format.xml  { head :ok }
	  end
	end
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Assignment 3</h1>

<div id="author-list">
<table>
    <th>Author</th>
  </tr>  
  <% for author in @authors %>
	  <td>
	    <span class="list-author"><%= h(author.first_name) + " " + h(author.last_name) %> </span><br />
		<% for book in author.books %>
		  <%= h(book.title) %>
		  <br>
		<% end %>
	  </td>
	  <td><%= link_to 'Show', author %></td>
      <% if get_current_user.admin? %>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, :confirm => 'Are you sure?', :method => :delete %></td>
	  <% end %>
    </tr>
<% end %>
</table>

<br>
<% if get_current_user.admin? %>
  <%= link_to 'New Author', new_author_path %>
<% end %>
</div>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @author.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @author.last_name %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>