config/routes.rb
Bookstore::Application.routes.draw do
  
  get "sessions/new"

  get "users/new"
  
  resources :books
  resources :authors
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :orders
  
  match '/books_search',  :to => 'shop#books_search'
  match '/authors_search', :to => 'shop#authors_search'
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/checkout', :to => 'orders#checkout'
  match '/done', :to => 'orders#done'

  match '/signup',  :to => 'users#new'
  match '/add_to_cart', :to => 'shop#add_to_cart'
  match '/clear_cart', :to => 'shop#clear_cart'
  match '/view_cart', :to => 'shop#view_cart'
  
	match '/watch_video', :to => 'shop#watch_video'
  match '/home_index', :to => 'shop#index'
  
  root :to => "shop#index"
  

end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  include SessionsHelper
  
  def index
    @title = "All books"
	@cart = get_cart
    # @books = Book.find_books_for_sale
	@books = Book.paginate(:page => params[:books_page], :per_page => 5)
  end

  def add_to_cart
    @cart = get_cart
    @cart.add_to_cart(Book.find(params[:id]))
	@books = Book.paginate(:page => params[:books_page], :per_page => 5)
	respond_to do |format|
	  format.html { render :action => "index" }
	  format.js
      format.xml  { render :xml => @book, :status => :created, :location => @book }
	end
  end
  
	def watch_video
		puts '*********************************'
		@book = Book.find(params[:id])
		respond_to do |format|
			# format.html { render :action => "watch_video" }
			# format.html { redirect_to watch_video.html.erb }
			format.html
      format.xml  { render :xml => @book }
		end
  end
	
  # Uses model to perform search
  def books_search
    @query = params[:query]
    @books = Book.search(@query)
	@books = @books.paginate(:page => params[:books_page], :per_page => 5)
	@cart = get_cart

	respond_to do |format|
      format.html { render :action => "index" }
      format.xml  { render :xml => @books }
    end
  end
  
  # Uses the model to search through authors
  def authors_search
    @query = params[:query]
    @authors = Author.search(@query)
	@books = []
	if !@authors.empty?  
	  @authors.each do |author|
	    puts author.last_name
	    author.books.each do |book|
		  puts book.title
	      @books << book unless @books.include?(book)
	    end
	  end
	end
	@books = @books.paginate(:page => params[:books_page], :per_page => 5)
	@cart = get_cart
	
	respond_to do |format|
      format.html { render :action => "index" }
      format.xml  { render :xml => @authors }
    end
  end
  
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/shop/_cart.html.erb
<ul>

<table id = carttable>
<th>Title</th>
<th>Price</th>
</tr>
<% for item in @cart.items %>
	<%= render :partial => 'cartitems', :locals => {:item => item} %>
	</tr>
<% end %>
</table>

<br>
Total
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
<%= number_to_currency h(@cart.total_price) %>
</ul>
<br><br>

  <% if signed_in? %>
    <%= button_to "Checkout", checkout_path, :class => "checkout_button round" %>
  <% else %>
    You must sign-in to checkout!
	<br>
    <%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
	&nbsp
    <%= link_to "Sign in", signin_path %>
  <% end %>
<br><br>
<%= link_to "Clear Cart", :action => "clear_cart" %>
&nbsp
<%= link_to "Return to Shopping", :action => "index" %>

app/views/shop/_cartitems.html.erb
<%= raw "<tr id='item_#{item.id}'>" %>

<td> <li><%= h(item.title) %> </td>
&nbsp&nbsp&nbsp&nbsp
<td> <%= h(item.price) %> </td>

app/views/shop/add_to_cart.html.erb
<h1>Your Cart</h1>

<%= render :partial => 'cart' %>


app/views/shop/clear_cart.html.erb
<h1>Your Cart is now cleared</h1>

<%= render :partial => 'cart' %>

<%= link_to "Return to Shopping", :action => "index" %>

app/views/shop/index.html.erb
<h1>Catalog</h1>
  <% form_tag books_search_path, :method => 'get' do %>
  <p>
    <%= text_field_tag (:query) %>
    <%= submit_tag "Search by Title" %>
  </p>
  <% end %>
  
  <% form_tag authors_search_path, :method => 'get' do %>
  <p>
    <%= text_field_tag (:query) %>
    <%= submit_tag "Search by Actor" %>
  </p>
  <% end %>

<div id="book-list">
<table>
    <th>Image</th>
    <th>Title</th>
    <th>Publisher</th>
    <th>Price</th>
  </tr>  
  <%= will_paginate @books, :param_name => 'books_page' %>
  <% for book in @books %>
      <td>
		  <img class="list-image" src="<%= book.image_url %>" width="100" />
  	  </td>
	  <td>
	    <span class="list-title"><%= link_to h(book.title), :action => "watch_video", :id => book %></span><br />
		<% for author in book.authors %>
		  <%= h(author.first_name) %>
		  <%= h(author.last_name) %>
		  <br>
		<% end %>
	  </td>
	  <td><%= book.publisher %>
	  <td><%= book.price %>
	  <td><%= button_to "Add to Cart", :action => :add_to_cart, :id => book %>
    </tr>
  <% end %>
</table>
<br>
<br>
<%= link_to "View Cart", :action => "view_cart" %>
</div>

app/views/shop/view_cart.html.erb
<h1>View Your Cart</h1>

<%= render :partial => 'cart' %>


app/views/shop/watch_video.html.erb
<div id="Sample" data_video=@book.title></div>
<h1>Requested Video</h1>
<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Publisher:</b>
  <%= @book.publisher %>
</p>

<p>
  <b>Price:</b>
  <%= @book.price %>
</p>

<video id="trailer" src="<%=@book.title + ".mp4"%>" controls poster="<%=@book.image_url%>" width="854" height="480">
</video>