config/routes.rb
Bookstore::Application.routes.draw do
  
  get "sessions/new"

  get "users/new"
  
  resources :books
  resources :authors
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :orders
  
  match '/books_search',  :to => 'shop#books_search'
  match '/authors_search', :to => 'shop#authors_search'
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/checkout', :to => 'orders#checkout'
  match '/done', :to => 'orders#done'

  match '/signup',  :to => 'users#new'
  match '/add_to_cart', :to => 'shop#add_to_cart'
  match '/clear_cart', :to => 'shop#clear_cart'
  match '/view_cart', :to => 'shop#view_cart'
  
	match '/watch_video', :to => 'shop#watch_video'
  match '/home_index', :to => 'shop#index'
  
  root :to => "shop#index"
  

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :run_before, :except => [:index, :show, :new, :edit, :destroy, :add_to_cart, :get_cart, :clear_cart, :view_cart]
  
  def run_before
    params[:book][:title] = params[:book][:title].humanize.titleize
	params[:book][:publisher] = params[:book][:publisher].humanize.titleize
  end
  
  def create_author(first, last)
    first = first.humanize.titleize
	last = last.humanize.titleize
    @author = Author.find_by_first_name_and_last_name(first, last)
    if @author == nil
	  name = {}
	  name["first_name"] = first
	  name["last_name"] = last
	  @author = Author.new(name) 
	  @author = nil unless @author.save
	end
  end
  
  # GET /books
  # GET /books.xml
  def index
    @books = Book.all
	# @book = Book.new

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @books }
    end
  end

  # GET /books/1
  # GET /books/1.xml
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @book }
    end
  end

  # GET /books/new
  # GET /books/new.xml
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.xml
  def create
    @book = Book.new(params[:book])
	create_author(params[:q],params[:r])

	if @author != nil
      respond_to do |format|
        if @book.save
	      @author.books << @book unless @author.books.include? @book
		  @author = nil
          format.html { redirect_to(@book, :notice => 'Book was successfully created.') }
		  # format.js
          format.xml  { render :xml => @book, :status => :created, :location => @book }
        else
          format.html { render :action => "new" }
		  # format.js { render :action => 'create_error' }
          format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
        end
      end
	else
	  respond_to do |format|
	    format.html { render :action => "new" }
		# correc the line below
		format.xml { render :xml => {@author=>["Author name is not valid"]}, :status => :unprocessable_entity }
	  end
	end
  end

  # PUT /books/1
  # PUT /books/1.xml
  def update
    @book = Book.find(params[:id])
	create_author(params[:q],params[:r])

    if @author != nil
	  respond_to do |format|
        if @book.update_attributes(params[:book])
	      @author.books << @book unless @author.books.include? @book
		  if params[:checks] != nil
	        params[:checks].each do |s|
		      if @book.authors.count > 1
	            @book.authors.delete(Author.find_by_id(s))
	          end
  	        end
	      end
		  @author = nil
          format.html { redirect_to(@book, :notice => 'Book was successfully updated.') }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @book.errors, :status => :unprocessable_entity }
        end
	  end
	else
	  respond_to do |format|
	    flash.now[:error] = 'Author name not valid'
	    respond_to do |format|
	      format.html { render :action => "edit" }
	    end
	  end
	end
  end

  def destroy
    puts "***************"
	@book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to(books_url) }
      format.xml  { head :ok }
    end
  end

  
  def add_to_cart
    @cart = get_cart
    @cart.add_to_cart(Book.find(params[:id]))
  end

  def get_cart
    if session[:cart]
      return session[:cart]
    else
      session[:cart] = Cart.new
      return session[:cart]
    end
  end
  
  def clear_cart
    @cart = get_cart
    @cart.clear
  end
  
  def view_cart
	@cart = get_cart
  end
  
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_cart.html.erb
<ul>
<% for item in @cart.items %>
	<li><%= h(item.title) %>
<% end %>
</ul>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :placeholder => 'Enter title here' %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br />
    <%= f.text_field :publisher, :placeholder => 'Publisher name' %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price, :placeholder => 'Enter a number greater than 0.01' %>
  </div>
  <div class="field">
    <%= f.label :inventory %><br />
	<%= f.text_field :inventory, :placeholder => 'Number of this book currently in inventory' %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
	<%= f.text_field :image_url, :placeholder => 'Enter image location' %>
  </div>
  <br>
  <b>Add an author for this book. To add more authors to this book, Edit the book.</b>
  <br><br>

  <b> For Editing Only: Check boxes for authors you want to remove. Minimum 1 author required. </b>
  <br>
  <ul class="checkbox-list">
    <% @book.authors.each do |author| -%>
      <li><%= check_box_tag 'checks[]', author.id %> <%= author.first_name %> <%= author.last_name %></li>
    <% end -%>
  </ul>
  
  <br><br>
  <%= label_tag(:q, "First Name:") %>
  <%= text_field_tag(:q) %>
  <br>
  <%= label_tag(:r, "Last Name:") %>
  <%= text_field_tag(:r) %>
  <%= submit_tag("Create") %>

<% end %>

app/views/books/add_to_cart.html.erb
<h1>Your Cart</h1>

<%= render :partial => 'cart' %>

<%= link_to "Clear Cart", :action => "clear_cart" %>
<%= link_to "Return to Shopping", :action => "index" %>

app/views/books/clear_cart.html.erb
<h1>Your Cart is now cleared</h1>

<%= render :partial => 'cart' %>

<%= link_to "Return to Shopping", :action => "index" %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>
<br>
If you do not want to add a new author, use one of the names below.
<br><br>
Authors already associated with this book. 
<br>
<td>
  <% for author in @book.authors %>
		  <%= h(author.first_name) %>
		  <%= h(author.last_name) %>
		  <br>
		<% end %>
  </td>

<br>
<br>  
<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Project</h1>

<div id="book-list">
<table>
    <th>Image</th>
    <th>Title</th>
    <th>Publisher</th>
    <th>Price</th>
	<th>Inventory</th>
  </tr>  
  <% for book in @books %>
      <td>
		  <img class="list-image" src="<%= book.image_url %>" width="100" />
  	  </td>
	  <td>
	    <span class="list-title"><%= h(book.title) %></span><br />
		<% for author in book.authors %>
		  <%= h(author.first_name) %>
		  <%= h(author.last_name) %>
		  <br>
		<% end %>
	  </td>
	  <td><%= book.publisher %>
	  <td><%= book.price %>
	  <td><%= book.inventory %>
	  <td><%= link_to 'Show', book %></td>
	  <% if get_current_user.admin? %>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, :confirm => 'Are you sure?', :method => :delete %></td>
	  <% end %>
    </tr>
<% end %>
</table>

<br>
<% if get_current_user.admin? %>
  <%= link_to 'New Book', new_book_path %>
<% end %>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Publisher:</b>
  <%= @book.publisher %>
</p>

<p>
  <b>Price:</b>
  <%= @book.price %>
</p>

<p>
  <b>Inventory:</b>
  <%= @book.inventory %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/view_cart.html.erb
<h1>View Your Cart</h1>

<%= render :partial => 'cart' %>

<%= link_to "Return to Shopping", :action => "index" %><br />
<%= link_to "Clear Cart", :action => "clear_cart" %>