config/routes.rb
Bookstore::Application.routes.draw do
  
  get "sessions/new"

  get "users/new"
  
  resources :books
  resources :authors
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :orders
  
  match '/books_search',  :to => 'shop#books_search'
  match '/authors_search', :to => 'shop#authors_search'
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/checkout', :to => 'orders#checkout'
  match '/done', :to => 'orders#done'

  match '/signup',  :to => 'users#new'
  match '/add_to_cart', :to => 'shop#add_to_cart'
  match '/clear_cart', :to => 'shop#clear_cart'
  match '/view_cart', :to => 'shop#view_cart'
  
	match '/watch_video', :to => 'shop#watch_video'
  match '/home_index', :to => 'shop#index'
  
  root :to => "shop#index"
  

end

app/views/layouts/_header.html.erb
<header>
  <nav class="round">
    <ul>
      <%= link_to "Home", root_path %>
	  <% if signed_in? %>
	  <%= link_to "Users", users_path %>
      <%= link_to "Profile", get_current_user %>
	  <%= link_to "Settings", edit_user_path(get_current_user) %>
      <% end %>
      <% if signed_in? %>
      <%= link_to "Sign out", signout_path, :method => :delete %>
      <% else %>
      <%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
	  <%= link_to "Sign in", signin_path %>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<% flash.each do |key, msg| %>
  <%= content_tag :div, msg, :class => [key, " message"], :id => "notice_ #{key}" %>
  <%= content_tag :script, :type => "text/javascript" do -%>
	setTimeout("new Effect.Highlite('notice_<%= key %>');", 1500);
  <% end %>
<% end %>
<br>
<%= yield %>

</body>
</html>

app/views/layouts/books.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Books: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold', 'book' %>
</head>
<body>
<div id="container">
	<div id="top">
	<h1>The Bookies</h1>
	</div>
	
	<div id="leftnav">
	<p>
	No this is not a gambling website
	</p>
	</div>
	
	<div id="content">

<p style="color: green"><%= flash[:notice] %></p>

<%= yield  %>

	</div>
	
	<div id="footer">
	Contact the webmaster at abc@gmail.com
	</div>
	
</div>

</body>
</html>

app/views/layouts/shop.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<%= render 'layouts/header' %>
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Books: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold', 'book' %>
</head>

<% flash.each do |key, msg| %>
  <%= content_tag :div, msg, :class => [key, " message"], :id => "notice_ #{key}" %>
  <%= content_tag :script, :type => "text/javascript" do -%>
	setTimeout("new Effect.Highlite('notice_<%= key %>');", 1500);
  <% end %>
<% end %>
<br>

<body>
<div id="container">
	<div id="top">
	<h1>Video Guru</h1>
	</div>
	
	<div id="leftnav">
	<p>
		How do you catch a rabbit? 
		Hide in a meadow and make carrot noises.
	</p>
	</div>
	
	<div id="content">
    <p style="color: green"><%= flash[:notice] %></p>
    <%= yield  %>
	</div>
	
	<div id="footer">
	Contact the webmaster at abc@gmail.com
	</div>
	
</div>

</body>
</html>